//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConanServerSwitcher.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConanServerSwitcher.Localization.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Server.
        /// </summary>
        public static string AddServer {
            get {
                return ResourceManager.GetString("AddServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new server entry..
        /// </summary>
        public static string AddServerToolTip {
            get {
                return ResourceManager.GetString("AddServerToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Settings.
        /// </summary>
        public static string ApplicationSettings {
            get {
                return ResourceManager.GetString("ApplicationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to start the game with this server?.
        /// </summary>
        public static string AreYouSureYouWishToStart {
            get {
                return ResourceManager.GetString("AreYouSureYouWishToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse for file.
        /// </summary>
        public static string BrowseForFile {
            get {
                return ResourceManager.GetString("BrowseForFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closes the application..
        /// </summary>
        public static string CloseToolTip {
            get {
                return ResourceManager.GetString("CloseToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy ModList.
        /// </summary>
        public static string CopyModList {
            get {
                return ResourceManager.GetString("CopyModList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy latest servermodlist.txt to new modlist..
        /// </summary>
        public static string CopyModListToolTip {
            get {
                return ResourceManager.GetString("CopyModListToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Server ModList.
        /// </summary>
        public static string CopyServerModList {
            get {
                return ResourceManager.GetString("CopyServerModList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Server.
        /// </summary>
        public static string DeleteServer {
            get {
                return ResourceManager.GetString("DeleteServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete server entry.
        /// </summary>
        public static string DeleteServerEntryCaption {
            get {
                return ResourceManager.GetString("DeleteServerEntryCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to delete this server entry?.
        /// </summary>
        public static string DeleteServerEntryMessage {
            get {
                return ResourceManager.GetString("DeleteServerEntryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletes the selected server entry..
        /// </summary>
        public static string DeleteServerToolTip {
            get {
                return ResourceManager.GetString("DeleteServerToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Server.
        /// </summary>
        public static string EditServer {
            get {
                return ResourceManager.GetString("EditServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edits the selected server entry..
        /// </summary>
        public static string EditServerToolTip {
            get {
                return ResourceManager.GetString("EditServerToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable files (*.exe)|*.exe.
        /// </summary>
        public static string ExecuteFilesFilter {
            get {
                return ResourceManager.GetString("ExecuteFilesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conan Exiles _Game Folder.
        /// </summary>
        public static string GameFolder {
            get {
                return ResourceManager.GetString("GameFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conan Exiles Easy Server Switcher.
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text files (*.txt)|*.txt|All files (*.*)|*.*.
        /// </summary>
        public static string ModFilesFilter {
            get {
                return ResourceManager.GetString("ModFilesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Mod list file.
        /// </summary>
        public static string ModListFile {
            get {
                return ResourceManager.GetString("ModListFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _OK.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application will only work on Windows OS, as it uses the Registry..
        /// </summary>
        public static string OnlyOnWindows {
            get {
                return ResourceManager.GetString("OnlyOnWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select game root folder.
        /// </summary>
        public static string SelectGameRootFolder {
            get {
                return ResourceManager.GetString("SelectGameRootFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select modlist file.
        /// </summary>
        public static string SelectModlistFile {
            get {
                return ResourceManager.GetString("SelectModlistFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Steam executable.
        /// </summary>
        public static string SelectSteamExecutable {
            get {
                return ResourceManager.GetString("SelectSteamExecutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server _Address.
        /// </summary>
        public static string ServerAddress {
            get {
                return ResourceManager.GetString("ServerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Server Name.
        /// </summary>
        public static string ServerName {
            get {
                return ResourceManager.GetString("ServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server _Port.
        /// </summary>
        public static string ServerPort {
            get {
                return ResourceManager.GetString("ServerPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the application settings..
        /// </summary>
        public static string SettingsToolTip {
            get {
                return ResourceManager.GetString("SettingsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Game.
        /// </summary>
        public static string StartGame {
            get {
                return ResourceManager.GetString("StartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts the Conan Exiles game and connects to the selected server..
        /// </summary>
        public static string StartGameToolTip {
            get {
                return ResourceManager.GetString("StartGameToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam _Executable.
        /// </summary>
        public static string SteamExecutable {
            get {
                return ResourceManager.GetString("SteamExecutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use BattlEye.
        /// </summary>
        public static string UseBattlEye {
            get {
                return ResourceManager.GetString("UseBattlEye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
